### ISSUE TITLE
Selected list is not set as Object when the value of id and name is same but set as just string

### ISSUE THREAD

**Issue by samu7** [NileshPatel17/ng-multiselect-dropdown#169]
When we multi-select the values there is a possibility that idField and textField can be same, in that case the selected list binds as string instead of object with id and text.

![id_text](https://user-images.githubusercontent.com/53810053/65173459-7671bf80-da6c-11e9-8fa1-fe6d3bed408e.png)

**Comment by sowmyadharg** [comment]
@NileshPatel17, I have faced the same problem, irrespective of the text and id can you make the selected items are always object

**Comment by NileshPatel17** [comment]
@samu7 by looking at the sample data, this is not goodpractice. Even if you have id and text identical, keep your model consistent.
{ client:"STEAASSYD",clientName:"STEAASSYD"}

**Comment by JairoFra** [comment]
@NileshPatel17 that is the default behaviour of the library. What @samu7 and @sowmyadharg are tying is just to avoid that behaviour. I am facing that same issue. I want my model to be consistent, but I am receiving an string instead an object when id and text have the same value.

**Comment by NileshPatel17** [comment]
@JairoFra this issue will be fixed in next release. Thanks!

**Comment by NileshPatel17** [comment]
it is fixed in new release 0.2.6

**Comment by carcigenicate** [comment]
This problem is not fixed, unfortunately. It's still present in 1.0.0. The weird thing is, `ngModelChange` fires *twice* on every change: once with the full object, then immediately after with just a string.

Edit: This ended up being causes by a problem on my end. I was accidentally feeding in a string instead of an array of objects into `ngModel` in some cases, and this was somehow causing the component to emit twice on all changes. So, if you're experiencing a similar problem, double check your input model.
