### ISSUE TITLE
Dropdown closes after each selection with singleSelection set to false

### ISSUE THREAD

**Issue by motohead400** [NileshPatel17/ng-multiselect-dropdown#331]
**Angular Version: 10.2.5**:

**Dropdown version: 0.3.4**:

**I have singleSelection set to false for the dropdown settings but it still closes after each selection.  I can still select multiple options but I have to click to open it back up after every selection**:

**Setup dropdown with below settings**:

**For dropdown to stay open while user is clicking options**:

**Dropdown closes after each selection is checked**:

Any relevant code:
Settings object:
` this.dropdownSettings = {
      singleSelection: false,      
      idField: 'Id',
      textField: 'Description',
      selectAllText: 'Select All',
      unSelectAllText: 'UnSelect All',
      itemsShowLimit: 10,
      allowSearchFilter: true      
    };`

Call in template
` <ng-multiselect-dropdown [placeholder]="'Product Categories'"
                                             [settings]="dropdownSettings"
                                             [data]="categoriesForProductAssociation"
                                             [(ngModel)]="selectedProduct.Categories"
                                             name="productCategories" #productCategories="ngModel">
                    </ng-multiselect-dropdown>`

**Comment by PlatiScript** [comment]
Hi, have you found a solution to solve this bug ?
Simon.

**Comment by motohead400** [comment]
Nope, haven't had a chance to dig any deeper into it.

**Comment by harshaldhake123** [comment]
Any update?

**Comment by dipaliwagh30** [comment]
> Any update?

did that issue resolve?

I'm also facing the same issue

**Comment by ashinamu** [comment]
I am also facing this issue, please suggest any solution

**Comment by ashinamu** [comment]
try version 0.2.10

**Comment by sadeveloper2000** [comment]
I am also facing same issue initially it was working fine then i implemented the filter sorting in that , after that it is closing immidiately the dropdown after selection and deselection. 
i have updated the version of that library, i tried to use the closeDropDownOnSelection property in the dorpdown settings too still it is troubling me

**Comment by Sriyanshjain27** [comment]
I am also facing this issue. Why is this not resolved even though it was opened years ago

**Comment by Sriyanshjain27** [comment]
@sadeveloper2000  did you achieve a work around?

**Comment by motohead400** [comment]
@Sriyanshjain27 I switched to https://github.com/ng-select/ng-select and it works perfectly.
